stages:
  - build

before_script:
  - git submodule init
  - git submodule update
  - apt-get update -qq && apt-get install -y -qq jq
  - chmod +x srdk
build_job:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:10.0
  rules:
    - if: '($CI_COMMIT_MESSAGE !~ /^doc:.*/ && $CI_COMMIT_DESCRIPTION !~ /!noCi/ && $CI_COMMIT_MESSAGE !~ /^chore:.*/) || $CI_COMMIT_DESCRIPTION =~ /!forceCi/'
  script:
    - ./srdk build
  artifacts:
    expire_in: 1 week
    paths:
      - '/builds/LiPolymer/OreUI-For-Everyone-1.21.1/build/'
